#ifndef APOENA_MSI_UMDF_RECOVERY_FIX44_FIX_FIELDS_HPP
#define APOENA_MSI_UMDF_RECOVERY_FIX44_FIX_FIELDS_HPP

#include <quickfix/Field.h>

namespace FIX
{
USER_DEFINE_NUMINGROUP( NoApplSeqNums, 10054 );
USER_DEFINE_INT( RawDataOffset, 10055 );
}

#endif /* APOENA_MSI_UMDF_RECOVERY_FIX44_FIX_FIELDS_HPP */

