#ifndef APOENA_MSI_UMDF_DECODER_QUICKFAST_UMDF_DECODER_QUICKFAST_PCH_HPP
#define APOENA_MSI_UMDF_DECODER_QUICKFAST_UMDF_DECODER_QUICKFAST_PCH_HPP

#define BOOST_MPL_CFG_NO_PREPROCESSED_HEADERS
#define BOOST_MPL_LIMIT_VECTOR_SIZE 40
#define BOOST_MPL_LIMIT_MAP_SIZE 40

#include <msi/msi_pch.hpp>

#ifdef _MSC_VER
#pragma warning(disable:4275)
#pragma warning(disable:4503)
#endif

#include <Application/QuickFAST.h>

#endif /* APOENA_MSI_UMDF_DECODER_QUICKFAST_UMDF_DECODER_QUICKFAST_PCH_HPP */

